Update recon.yml

diff --git a/.github/workflows/recon.yml b/.github/workflows/recon.yml
--- a/.github/workflows/recon.yml
+++ b/.github/workflows/recon.yml
@@ -42,20 +42,22 @@ jobs:
       - name: Check If Done
         run: |
           curl -sSLO "https://github.com/frankyeh/DSI-Studio/releases/download/2024.06.12/dsi_studio_ubuntu2004.zip" && unzip -q *.zip
-          wget -q https://github.com/frankyeh/DSI-Studio-Cloud/releases/download/${{ github.event.inputs.id }}/${{ matrix.files }}_dwi.gqi.fib.gz || true
-          wget -q https://github.com/frankyeh/DSI-Studio-Cloud/releases/download/${{ github.event.inputs.id }}/${{ matrix.files }}_dwi.qsdr.fib.gz || true
-          if [ ! -f "${{ matrix.files }}_dwi.qsdr.fib.gz" ]; then
-            echo "file_exists=false" >> $GITHUB_ENV
-          else
+          if curl --head --silent --fail https://github.com/frankyeh/DSI-Studio-Cloud/releases/download/${{ inputs.dataset_id }}/${file}_dwi.qsdr.fib.gz; then
             echo "file_exists=true" >> $GITHUB_ENV
+          else
+            echo "file_exists=false" >> $GITHUB_ENV
           fi
       - name: GQI and QSDR Reconstruction
         if: env.file_exists == 'false'
         run: |
-          wget -q https://github.com/frankyeh/DSI-Studio-Cloud/releases/download/${{ github.event.inputs.id }}/${{ matrix.files }}_dwi.src.gz
-          ./dsi-studio/dsi_studio --action=rec --source=${{ matrix.files }}_dwi.src.gz --output=${{ matrix.files }}_dwi.gqi.fib.gz ${{ github.event.inputs.src_param}}  
-          ./dsi-studio/dsi_studio --action=rec --source=${{ matrix.files }}_dwi.src.gz --output=${{ matrix.files }}_dwi.qsdr.fib.gz --method=7  ${{ github.event.inputs.src_param}}
-
+          if curl --head --silent --fail https://github.com/frankyeh/DSI-Studio-Cloud/releases/download/${{ inputs.dataset_id }}/${file}_dwi.src.gz; then
+            wget -q https://github.com/frankyeh/DSI-Studio-Cloud/releases/download/${{ inputs.dataset_id }}/${{ matrix.files }}_dwi.src.gz
+            ./dsi-studio/dsi_studio --action=rec --source=${{ matrix.files }}_dwi.src.gz --output=${{ matrix.files }}_dwi.gqi.fib.gz ${{ github.event.inputs.src_param}}  
+            ./dsi-studio/dsi_studio --action=rec --source=${{ matrix.files }}_dwi.src.gz --output=${{ matrix.files }}_dwi.qsdr.fib.gz --method=7  ${{ github.event.inputs.src_param}}
+          else
+            echo "ERROR: no SRC file ${file}_dwi.src.gz for reconstruction " >&2
+            exit 1
+          fi
       - name: Create Release
         if: env.file_exists == 'false'
         env:
